<?php

namespace App\Command;

use App\Dto\ParsedArticle;
use App\Dto\ParsedFeed;
use App\Entity\Article;
use App\Entity\Feed;
use App\Feed\FeedType;
use App\Feed\FeedTypeDetector;
use App\Feed\Parser\FeedAtomParser;
use App\Feed\Parser\FeedJsonParser;
use App\Feed\Parser\FeedParserInterface;
use App\Feed\Parser\FeedRss2Parser;
use App\Repository\ArticleRepository;
use App\Repository\FeedRepository;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\AutowireLocator;
use Symfony\Component\DependencyInjection\ServiceLocator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;

#[AsCommand(
    name: 'app:feed:poll',
    description: 'Once parse rss feed is generated by the app',
)]
class FeedPollCommand extends Command
{

    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly HttpClientInterface    $httpClient,
        private readonly FeedRepository         $feedRepository,
        private readonly ArticleRepository      $articleRepository,
        private readonly FeedTypeDetector       $feedTypeDetector,
        #[AutowireLocator([FeedAtomParser::class, FeedRss2Parser::class, FeedJsonParser::class])]
        private readonly ServiceLocator         $feedParsersLocator,
    )
    {
        parent::__construct();
    }

    /**
     * @param ParsedFeed $parsedFeed
     * @return int[]
     */
    public function handleFeed(ParsedFeed $parsedFeed, Feed $feed): array
    {
        $skipped = $created = $noGuid = 0;

        /** @var ParsedArticle $item */
        foreach ($parsedFeed->articles as $item) {
            $guid = isset($item->guid) ? (string) $item->guid : null;
            $link = isset($item->link) ? (string) $item->link : null;
            $key = $guid ?? $link;
            if ($key === null) {
                continue;
            }
            if ($guid === null && $link !== null) {
                $noGuid++;
            }

            $count = $this->articleRepository->count([
                'feed' => $feed,
                'guid' => $key,
            ]);

            if ($count > 0) {
                $skipped++;
                continue;
            }

            $article = new Article();
            $article->setFeed($feed);
            $article->setGuid($key);
            $article->setUrl($item->url);
            $article->setTitle((string)$item->title);
            $article->setSummary(isset($item->description) ? (string)$item->description : null);
            $article->setPublishedAt($this->getPubDate($item->pubDate ?? null));

            $this->entityManager->persist($article);

            $created++;
        }

        $feed->setLastPolledAt(new \DateTimeImmutable());
        $this->entityManager->flush();

        return array($created, $skipped, $noGuid);
    }

    /**
     * @param mixed $url
     * @return Feed[]|array|object[]
     */
    private function getFeeds(mixed $url): array
    {
        $feeds = [];
        if ($url !== null) {
            $feed = $this->feedRepository->findOneBy([
                'url' => $url
            ]);
            if ($feed instanceof Feed) {
                $feeds[] = $feed;
            }
        } else {
            $feeds = $this->feedRepository->findAll();
        }
        return $feeds;
    }

    protected function configure(): void
    {
        $this
            ->addArgument('url', InputArgument::OPTIONAL, 'Optional url for processing')
        ;
    }

    /**
     * @throws TransportExceptionInterface
     * @throws \Exception
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $argUrl = $input->getArgument('url');

        $feeds = $this->getFeeds($argUrl);

        if (empty($feeds)) {
            $io->error('No feeds found');
            return Command::FAILURE;
        }

        $totalCreated = $totalSkipped = $totalNoGuid = 0;
        $row = [];
        foreach ($feeds as $feed) {
            $url = $feed->getUrl();
            $response = $this->httpClient->request(Request::METHOD_GET, $url);

            if ($response->getStatusCode() !== Response::HTTP_OK) {
                $io->warning('Status Code: ' . $response->getStatusCode());
                continue;
            }

            $body = $response->getContent();

            $feedType = $this->feedTypeDetector->detect($body, $response->getHeaders()['content-type'][0] ?? null);

            $feedParser = match ($feedType->name) {
                FeedType::JsonFeed->name => FeedJsonParser::class,
                FeedType::Atom->name     => FeedAtomParser::class,
                FeedType::Rss->name      => FeedRss2Parser::class,
            };

            /** @var FeedParserInterface $feedParser */
            $feedParser = $this->feedParsersLocator->get($feedParser);

            $parsedFeed = $feedParser->parse($body);

            list($created, $skipped, $noGuid) = $this->handleFeed($parsedFeed, $feed);
            $row[] = [$url, $created, $skipped];
            $totalCreated += $created; $totalSkipped += $skipped; $totalNoGuid += $noGuid;
        }

        $io->comment(sprintf('Use link instead guid %s times', $totalNoGuid));

        $io->table(['Url', 'Created', 'Skipped'], $row);

        $io->success(sprintf('All created %s articles, skipped %s articles', $totalCreated, $totalSkipped));

        return Command::SUCCESS;
    }

    private function getPubDate(string|null $date): ?DateTimeImmutable
    {
        if ($date === null) {
            return null;
        }

        $result = null;

        try {
            $result = new \DateTimeImmutable($date);
        } catch (\Exception) {}

        return $result;
    }
}
