<?php

namespace App\Command;

use App\Entity\Feed;
use App\Message\PollFeedMessage;
use App\Repository\FeedRepository;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Messenger\MessageBusInterface;

#[AsCommand(
    name: 'app:feed:poll',
    description: 'Once parse rss feed is generated by the app',
)]
class FeedPollCommand extends Command
{
    public function __construct(
        private readonly FeedRepository           $feedRepository,
        private readonly MessageBusInterface      $messageBus,
    )
    {
        parent::__construct();
    }

    /**
     * @param mixed $url
     * @return Feed[]|array|object[]
     */
    private function getFeeds(mixed $url): array
    {
        $feeds = [];
        if ($url !== null) {
            $feed = $this->feedRepository->findOneBy([
                'url' => $url
            ]);
            if ($feed instanceof Feed) {
                $feeds[] = $feed;
            }
        } else {
            $feeds = $this->feedRepository->findAll();
        }
        return $feeds;
    }

    protected function configure(): void
    {
        $this
            ->addArgument('url', InputArgument::OPTIONAL, 'Optional url for processing')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $argUrl = $input->getArgument('url');

        $feeds = $this->getFeeds($argUrl);

        if (empty($feeds)) {
            $io->error('No feeds found');
            return Command::FAILURE;
        }

        foreach ($feeds as $feed) {
            $this->messageBus->dispatch(new PollFeedMessage($feed->getId()));
        }

        return Command::SUCCESS;
    }
}
