<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260828092224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guid VARCHAR(500) NOT NULL, url VARCHAR(2048) NOT NULL, title VARCHAR(512) NOT NULL, summary TEXT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, feed_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_23A0E6651A5BC03 ON article (feed_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E6651A5BC032B6FCFB2 ON article (feed_id, guid)');
        $this->addSql('CREATE TABLE feed (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(500) NOT NULL, type VARCHAR(16) NOT NULL, title VARCHAR(255) DEFAULT NULL, last_polled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_234044AB953C1C61 ON feed (source_id)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, homepage_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6651A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feed ADD CONSTRAINT FK_234044AB953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP CONSTRAINT FK_23A0E6651A5BC03');
        $this->addSql('ALTER TABLE feed DROP CONSTRAINT FK_234044AB953C1C61');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE feed');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
